# Generated by Django 5.1.2 on 2024-11-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='foundation_year',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='website_url',
        ),
    ]
