# Generated by Django 5.1.2 on 2024-11-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_businessprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
