# Generated by Django 5.1.2 on 2024-11-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_businessprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='facebook_url',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='businessprofile',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
    ]
