# Generated by Django 5.1 on 2024-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('destinations', '0002_destination_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.ManyToManyField(related_name='destinations', to='core.tag'),
        ),
    ]
