# Generated by Django 5.1 on 2024-09-08 08:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
