# Generated by Django 5.1.2 on 2024-11-11 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activitycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory'),
            preserve_default=False,
        ),
    ]
