# Generated by Django 5.1.2 on 2024-11-23 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activities_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='time',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='activities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
