# Generated by Django 5.1.2 on 2024-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_rename_time_activities_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='image2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='image3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
