# Generated by Django 5.1.2 on 2024-11-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_image_alter_hotel_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='highlights',
            field=models.ManyToManyField(blank=True, related_name='hotels_highlights', to='hotels.highlights'),
        ),
    ]
