# Generated by Django 5.1.2 on 2024-11-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_highlights_hotel_website_hotel_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
