# Generated by Django 5.1.2 on 2024-11-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_hotelrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.category'),
            preserve_default=False,
        ),
    ]
