# Generated by Django 5.1.2 on 2024-11-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_hotel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-created_at']},
        ),
    ]
