# Generated by Django 5.1.2 on 2024-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_alter_hotel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
