# Generated by Django 5.1.2 on 2024-11-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_alter_hotel_lat_alter_hotel_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
