# Generated by Django 5.1.2 on 2024-11-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destinationrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image6',
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image3',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image4',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image5',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
