# Generated by Django 5.1.2 on 2024-11-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_remove_destination_image6_alter_destination_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='destination',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
    ]
