# Generated by Django 5.1.2 on 2024-11-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_remove_destination_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='cost',
        ),
        migrations.AddField(
            model_name='destination',
            name='time',
            field=models.IntegerField(blank=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
