# Generated by Django 5.1.2 on 2024-10-25 18:04

import backend.core.validators
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50, validators=[backend.core.validators.validate_start_with_upper], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, validators=[backend.core.validators.validate_start_with_upper])),
                ('city', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, max_length=70, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, max_length=50, null=True)),
                ('github', models.URLField(blank=True, max_length=50, null=True)),
                ('about', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, validators=[backend.core.validators.validate_phone_number])),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
